baseURL = "https://www.roppongivc.com/"
title = "六本木ベンチャーキャピタル"
defaultContentLanguage = "ja"
enableRobotsTXT = true
paginate = 12

[languages]
  [languages.ja]
    languageName = "JP"
    weight = 1
    title = "六本木ベンチャーキャピタル"
    [languages.ja.params]
      description = "日本最高峰のSTEM頭脳に、世界最高峰の起業家体験を。"
    [[languages.ja.menus.main]]
      name = "Members"
      url = "/members/"
      weight = 1
    [[languages.ja.menus.main]]
      name = "Media"
      url = "/jiwa/"
      weight = 2
  [languages.en]
    languageName = "EN"
    weight = 2
    title = "Roppongi Venture Capital"
    [languages.en.params]
      description = "World-class entrepreneurial experiences for Japan's brightest STEM minds."
    [[languages.en.menus.main]]
      name = "Members"
      url = "/en/members/"
      weight = 1
    [[languages.en.menus.main]]
      name = "Media"
      url = "/en/jiwa/"
      weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      table = true
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
  pillar = "pillars"
