baseURL = "https://roppongivc.com/"
title = "六本木ベンチャーキャピタル"
languageCode = "ja"
defaultContentLanguage = "ja"
enableRobotsTXT = true
paginate = 12

[params]
  description = "日本最高峰のSTEM頭脳に、世界最高峰の起業家体験を。"

[menus]
  [[menus.main]]
    name = "Members"
    url = "/members/"
    weight = 1
  [[menus.main]]
    name = "Media"
    url = "/jiwa/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[taxonomies]
  tag = "tags"
  pillar = "pillars"
